apiVersion: v1
kind: Pod
metadata:
    name: guestbook-app-pod
    labels:
        name: guestbook-app-pod
        app: guestbook-app
spec:
    containers:
    - name: guestbook-app
      image: gcr.io/google-samples/gb-frontend:v4 
      ports:
      - containerPort: 80
