apiVersion: v1
kind: Pod
metadata:
    name: redis-guestboook-pod
    labels:
        name: redis-guestbook-pod
        app: guestbook-app
spec:
    containers:
    - name: redis
      image: redis
      ports:
      - containerPort: 6379
