apiVersion: v1
kind: Service
metadata:
  name: redis-guestbook
  labels:
    name: redis-guestbook-service
    app: guestbook-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
      name: redis-guestboook-pod
      app: guestbook-app
